/**
 * French infinitive glosses for SEPARABLE_GLOSS (keys ⊆ SEPARABLE_INFINITIVES).
 * Curated to match EN/ES/IT infinitive style — not conjugated forms (e.g. offrir, not offre).
 */
export const SEPARABLE_GLOSS_FR = Object.freeze({
  mitmachen: 'participer',
  mitnehmen: 'emmener',
  mitbringen: 'apporter',
  mitkommen: 'venir avec',
  mitteilen: 'informer',
  mitspielen: 'jouer avec',
  aufmachen: 'ouvrir',
  aufnehmen: 'enregistrer',
  aufräumen: 'ranger',
  aufstehen: 'se lever',
  aufhören: 'arrêter',
  aufpassen: 'faire attention',
  aufgeben: 'abandonner',
  aufbauen: 'construire',
  aufschreiben: 'noter',
  auffallen: 'attirer l\'attention',
  aufwachen: 'se réveiller',
  anmachen: 'allumer',
  anrufen: 'appeler',
  anfangen: 'commencer',
  ankommen: 'arriver',
  ankündigen: 'annoncer',
  anbieten: 'offrir',
  ansehen: 'regarder',
  anziehen: 'mettre',
  anmelden: 's\'inscrire',
  anschauen: 'regarder',
  ausmachen: 'éteindre',
  ausschalten: 'éteindre',
  aussehen: 'avoir l\'air',
  ausziehen: 'se déshabiller',
  ausfüllen: 'remplir',
  ausgeben: 'dépenser',
  aussteigen: 'descendre',
  ausprobieren: 'essayer',
  auswählen: 'choisir',
  ausdenken: 'inventer',
  einladen: 'inviter',
  einkaufen: 'faire les courses',
  einschalten: 'allumer',
  einnehmen: 'prendre',
  einsteigen: 'monter',
  einpacken: 'empaqueter',
  einschlafen: 's\'endormir',
  eintragen: 'inscrire',
  einziehen: 'emménager',
  einfallen: 'venir à l\'esprit',
  zumachen: 'fermer',
  zubereiten: 'préparer',
  zuhören: 'écouter',
  zugeben: 'admettre',
  vorbereiten: 'préparer',
  vorschlagen: 'proposer',
  vorstellen: 'présenter',
  vorhaben: 'prévoir',
  vorlesen: 'lire à voix haute',
  vorkommen: 'se produire',
  nachdenken: 'réfléchir',
  nachfragen: 's\'informer',
  nachschauen: 'vérifier',
  nachweisen: 'prouver',
  beibringen: 'enseigner',
  beitragen: 'contribuer',
  losfahren: 'partir',
  losgehen: 'se mettre en route',
  weggehen: 'partir',
  wegfahren: 'partir en voiture',
  zurückkommen: 'revenir',
  zurückgeben: 'rendre',
  weitergehen: 'continuer',
  weitermachen: 'continuer',
  teilnehmen: 'participer',
  stattfinden: 'avoir lieu',
  kennenlernen: 'faire connaissance',
  abholen: 'aller chercher',
  absagen: 'annuler',
  abschließen: 'conclure',
  abfahren: 'partir',
  abgeben: 'remettre',
  festhalten: 'retenir',
  feststellen: 'constater',
  herstellen: 'produire',
  herkommen: 'venir',
  mithelfen: 'aider',
  mitschreiben: 'prendre des notes',
  aufklären: 'clarifier',
  auflegen: 'raccrocher',
  aufregen: 'contrarier',
  aufteilen: 'diviser',
  angeben: 'indiquer',
  ansprechen: 's\'adresser à',
  anbauen: 'cultiver',
  anfragen: 'demander',
  anwenden: 'appliquer',
  anprobieren: 'essayer',
  anklicken: 'cliquer',
  ankreuzen: 'cocher',
  ausgehen: 'sortir',
  austauschen: 'échanger',
  ausdrucken: 'imprimer',
  aussuchen: 'choisir',
  ausschließen: 'exclure',
  ausschneiden: 'découper',
  einreichen: 'déposer',
  einräumen: 'ranger',
  einsparen: 'économiser',
  einteilen: 'organiser',
  zustimmen: 'approuver',
  zurückrufen: 'rappeler',
  weitergeben: 'transmettre',
  hingehen: 'y aller',
  abmelden: 'se désinscrire',
  abnehmen: 'perdre du poids',
  zunehmen: 'prendre du poids',
  ablehnen: 'refuser',
  abstellen: 'éteindre',
  festlegen: 'fixer',
  umsteigen: 'changer',
  umziehen: 'déménager',
  umsetzen: 'mettre en œuvre',
  durchführen: 'réaliser',
  übernehmen: 'reprendre',
  überweisen: 'virer',
  unterschreiben: 'signer',
  zusammenfassen: 'résumer',
});

/** True when French gloss uses infinitive(s), not conjugated 3sg (e.g. offre). */
export function isFrenchInfinitiveGloss(text) {
  const t = String(text || '').trim().toLowerCase();
  if (!t) return false;
  const conjugated =
    /^(offre|propose|produit|fait|va|vient|met|appelle|prend|écoute|regarde|ouvre|ferme|sort|entre|part|revient)$/i;
  const words = t.split(/\s+/).map((w) => w.replace(/^[^a-zàâäæçéèêëïîôùûüœ]+|[^a-zàâäæçéèêëïîôùûüœ]+$/gi, ''));
  for (const w of words) {
    if (!w) continue;
    if (conjugated.test(w)) return false;
    if (/^(?:se|s')/.test(w)) return true;
    if (/(?:er|ir|re|oir)$/.test(w)) return true;
  }
  if (/\by aller\b/.test(t)) return true;
  if (/\bavoir lieu\b/.test(t)) return true;
  if (/\bfair(?:e|e les)\b/.test(t)) return true;
  return false;
}
