/**
 * Italian infinitive glosses for SEPARABLE_GLOSS (keys ⊆ SEPARABLE_INFINITIVES).
 * Curated to match EN/ES infinitive style — not conjugated forms (e.g. offrire, not offre).
 */
export const SEPARABLE_GLOSS_IT = Object.freeze({
  mitmachen: 'partecipare',
  mitnehmen: 'portare con sé',
  mitbringen: 'portare',
  mitkommen: 'venire insieme',
  mitteilen: 'comunicare',
  mitspielen: 'giocare insieme',
  aufmachen: 'aprire',
  aufnehmen: 'registrare',
  aufräumen: 'riordinare',
  aufstehen: 'alzarsi',
  aufhören: 'smettere',
  aufpassen: 'fare attenzione',
  aufgeben: 'arrendersi',
  aufbauen: 'costruire',
  aufschreiben: 'scrivere',
  auffallen: 'colpire',
  aufwachen: 'svegliarsi',
  anmachen: 'accendere',
  anrufen: 'telefonare',
  anfangen: 'iniziare',
  ankommen: 'arrivare',
  ankündigen: 'annunciare',
  anbieten: 'offrire',
  ansehen: 'guardare',
  anziehen: 'indossare',
  anmelden: 'registrarsi',
  anschauen: 'guardare',
  ausmachen: 'spegnere',
  ausschalten: 'spegnere',
  aussehen: 'sembrare',
  ausziehen: 'spogliarsi',
  ausfüllen: 'compilare',
  ausgeben: 'spendere',
  aussteigen: 'scendere',
  ausprobieren: 'provare',
  auswählen: 'scegliere',
  ausdenken: 'inventare',
  einladen: 'invitare',
  einkaufen: 'fare la spesa',
  einschalten: 'accendere',
  einnehmen: 'assumere',
  einsteigen: 'salire',
  einpacken: 'impacchettare',
  einschlafen: 'addormentarsi',
  eintragen: 'annotare',
  einziehen: 'trasferirsi',
  einfallen: 'venire in mente',
  zumachen: 'chiudere',
  zubereiten: 'preparare',
  zuhören: 'ascoltare',
  zugeben: 'ammettere',
  vorbereiten: 'preparare',
  vorschlagen: 'proporre',
  vorstellen: 'presentare',
  vorhaben: 'progettare',
  vorlesen: 'leggere ad alta voce',
  vorkommen: 'verificarsi',
  nachdenken: 'riflettere',
  nachfragen: 'informarsi',
  nachschauen: 'controllare',
  nachweisen: 'dimostrare',
  beibringen: 'insegnare',
  beitragen: 'contribuire',
  losfahren: 'partire',
  losgehen: 'mettersi in cammino',
  weggehen: 'andarsene',
  wegfahren: 'partire',
  zurückkommen: 'tornare',
  zurückgeben: 'restituire',
  weitergehen: 'continuare',
  weitermachen: 'continuare',
  teilnehmen: 'partecipare',
  stattfinden: 'svolgersi',
  kennenlernen: 'conoscere',
  abholen: 'andare a prendere',
  absagen: 'annullare',
  abschließen: 'concludere',
  abfahren: 'partire',
  abgeben: 'consegnare',
  festhalten: 'trattenere',
  feststellen: 'constatare',
  herstellen: 'produrre',
  herkommen: 'provenire',
  mithelfen: 'aiutare',
  mitschreiben: 'prendere appunti',
  aufklären: 'chiarire',
  auflegen: 'riagganciare',
  aufregen: 'turbare',
  aufteilen: 'dividere',
  angeben: 'indicare',
  ansprechen: 'rivolgersi a',
  anbauen: 'coltivare',
  anfragen: 'richiedere',
  anwenden: 'applicare',
  anprobieren: 'provare',
  anklicken: 'cliccare',
  ankreuzen: 'spuntare',
  ausgehen: 'uscire',
  austauschen: 'scambiare',
  ausdrucken: 'stampare',
  aussuchen: 'scegliere',
  ausschließen: 'escludere',
  ausschneiden: 'ritagliare',
  einreichen: 'presentare',
  einräumen: 'riporre',
  einsparen: 'risparmiare',
  einteilen: 'organizzare',
  zustimmen: 'acconsentire',
  zurückrufen: 'richiamare',
  weitergeben: 'trasmettere',
  hingehen: 'andare lì',
  abmelden: 'cancellarsi',
  abnehmen: 'perdere peso',
  zunehmen: 'aumentare',
  ablehnen: 'rifiutare',
  abstellen: 'spegnere',
  festlegen: 'stabilire',
  umsteigen: 'cambiare',
  umziehen: 'traslocare',
  umsetzen: 'attuare',
  durchführen: 'eseguire',
  übernehmen: 'subentrare',
  überweisen: 'trasferire',
  unterschreiben: 'firmare',
  zusammenfassen: 'riassumere',
});

/** True when Italian gloss uses infinitive(s), not conjugated 3sg (e.g. offre). */
export function isItalianInfinitiveGloss(text) {
  const t = String(text || '').trim().toLowerCase();
  if (!t) return false;
  const words = t.split(/\s+/).map((w) => w.replace(/[^a-zàèéìòóù']/gi, ''));
  const conjugated = /^(offre|offre|propone|produce|fa|va|ha|viene|mette|chiama|prende|ascolta|guarda|apre|chiude|esce|entra)$/i;
  for (const w of words) {
    if (!w) continue;
    if (conjugated.test(w)) return false;
    if (/(?:are|ere|ire|arsi|ersi|irsi|orre|urre|enere)$/.test(w)) return true;
  }
  if (/\bandarsene\b/.test(t)) return true;
  return false;
}
